# 异常的传播（抛出异常）
#    函数中出现异常时，
#    如果在函数中对异常进行了处理，则异常不会再继续传播,
#    如果函数中没有对异常进行处理，则异常会继续向函数调用处传播,
#    如果函数调用处处理了异常，则不再传播，如果没有处理则继续向调用处传播,
#    直到传递到全局作用域（主模块）如果依然没有处理，则程序终止，并且显示异常信息。
def fn():
    print('---------- fn ----------')
    print(a)
    print(10 / 0)


def fn2():
    print('---------- fn2 ----------')
    fn()


def fn3():
    print('---------- fn3 ----------')
    fn2()


fn3()

# try:
#     fn3()
# except:
#     print('except,出错了')
# else:
#     print('else,正常')
# finally:
#     print('finally,总会执行')

print('------------------------- 程序执行结束 -------------------------')
